### ISSUE TITLE
[Bug] Cambiar el valor de `main` en el `package.json` 

### ISSUE THREAD

**Issue by ivandevp** [Pamela-C-Torres-Gtz/MEX008-FE-md-link#13]
Según el `package.json` el punto de entrada para usar esta librería es:

```
{
  ...
  "main": "index.js",
  ...
}
```

Sin embargo, en el proyecto no existe ese archivo. Debería ser `src/index.js`?

Si es así, el `src/index.js` debería ir juntando la ejecución de las demás librerías porque en este momento aparenta no estar funcionando o funcionar solo los archivos por separado.

**Comment by ivandevp** [comment]
Aquí puedes ver la importancia del `main`: https://docs.npmjs.com/files/package.json#main

**Comment by Pamela-C-Torres-Gtz** [comment]
ok, gracias, la verdad no habia contemplado y se gun lo que había investigado el main indicaba mi archivo principal de ejecución, el cual era el index.js, no sabia que lo tenia que manejar pero con el nombre de mi carpeta principal src.

Gracias por la documentación me esta sirviendo demasiado y lo aplicare

**Comment by Pamela-C-Torres-Gtz** [comment]
listo
