### ISSUE TITLE
[Feature] Usar babel-node para ejecutar código de node

### ISSUE THREAD

**Issue by ivandevp** [Pamela-C-Torres-Gtz/MEX008-FE-md-link#14]
Ya que usas módulos que se transpilan con `babel` para usarlos dentro de tus tests, tu código de `node` no se puede ejecutar nativamente. Una propuesta de solución sería usar `babel-node` para que se encargue de transpilarlo y ejecutar el código transpilado. Aquí una guía que tal vez te pueda ayudar: https://www.codementor.io/osazeedoosagie/easy-set-up-babel-7-for-nodejs-rg3zak6pj

**Comment by Pamela-C-Torres-Gtz** [comment]
Muchas gracias por las recomendaciones y quedo listo. 👍
